export const Icons = {
  heart: String.fromCharCode(0xf32e),
  heartOutline: String.fromCharCode(0xf33b),
  play: String.fromCharCode(0xf472),
  back: String.fromCharCode(0xf208),
  star: String.fromCharCode(0xf535),
  menu: String.fromCharCode(0xf3fd),
  close: String.fromCharCode(0xf223),
  home: String.fromCharCode(0xf346),
  account: String.fromCharCode(0xf451),
  downloads: String.fromCharCode(0xf289),
  settings: String.fromCharCode(0xf1a2),
  notifications: String.fromCharCode(0xf421),
  help: String.fromCharCode(0xf18d),
  info: String.fromCharCode(0xf35a),
  share: String.fromCharCode(0xf51a),
  filter: String.fromCharCode(0xf2f5),
  search: String.fromCharCode(0xf505),
  check: String.fromCharCode(0xf207),
  comment: String.fromCharCode(0xf1ec),
  warn: String.fromCharCode(0xf5ba),
  filmOutline: String.fromCharCode(0xf2cc),
  edit: String.fromCharCode(0xf448),
  save: String.fromCharCode(0xf4fa),
};
